#!/usr/bin/env bash
# installing a nginx server
sudo apt-get update
sudo apt-get -y intsall nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
