#!/usr/bin/env bash
# installing a nginx server

sudo apt-get update
sudo apt-get -y intsall nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index-debian.html
sudo service nginx restart
