#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" | sudo tee /etc/nginx/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html
sudo echo "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
        root /etc/nginx/html;
	internal;
    }
    }" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
