#!/usr/bin/env bash
# installing a load balancer
sudo apt-get -y update
sudo apt-get install -y haproxy

sudo echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo touch /etc/haproxy/haproxy.cfg

sudo echo "
    defaults
        mode http
	
    frontend rekool.tech
        bind 0.0.0.0:80
	default_backend web_servers
	
    backend web_servers
        balance roundrobin
	server 302852-web-01 100.26.154.225:80 check
	server 302852-web-02 54.205.218.5:80 check
	" | sudo tee /etc/haproxy.haproxy.cfg

sudo service haproxy restart
