#!/usr/bin/env bash
#  a Bash script with the minimum number of commands to automate your fix.
sudo rm etc/nginx/sites-enable/default
sudo ln -s etc/nginx/sites-available/default etc/nginx/sites-enable/default
sudo service nginx restart
