#!/usr/bin/env bash
# a script that loop from 1 to 10
# prints bad luck for the 4th position
# prints good luck for the 8th position
# prints Best School for the rest
i=0
while ((i < 10))
do
	((i++))
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
