#!/usr/bin/env bash
# writing a script that displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59
Hour=0
Minutes=1
while [[ Hour -lt 13 ]]
do
	echo "Hour: $Hour"
	((Hour++))
	while [[ Minutes -lt 60 ]]
	do
		echo $Minutes
		((Minutes++))
	done
	((Minutes=1))
done
