#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
new_list=$(ls)
for i in $new_list
do
	echo "$i"
done
