#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.new
new_host="127.0.0.2"
new_fb="8.8.8.8"
sed -i "/^127\.0\.0\.1[[: :]]\+localhost[[: :]]*$/s/.*/$new_host localhost/" ~/hosts.new
sed -i "/^.*[[: :]]facebook.com[[: :]]*$/s/.*/$new_fb facebook.com/" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
