#!/usr/bin/env bash
# running nginx as Nginx
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-available/default
su nginx -s /bin/bash -c 'service nginx restart'
