#!/usr/bin/env bash
# running nginx as Nginx in less than 7 lines
pkill -f apache2
chown -R nginx:nginx /etc/nginx
chown -R nginx:nginx /etc/share/nginx
chmod 755 -R /etc/nginx/
sed -i 's/listen 80 default server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default server;/listen \[::\]:8080 default_server;/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
